// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMT3siRubQdeTke30ThJFw_HxWSfPyBuw',
    appId: '1:627288522489:android:f9f65d92d11a43fa8f6c28',
    messagingSenderId: '627288522489',
    projectId: 'campusfind-26ac2',
    storageBucket: 'campusfind-26ac2.firebasestorage.app',
  );
}
